# Generated by Django 5.2.9 on 2026-08-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_devicetoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("order_placed", "Order placed"),
                    ("order_approved", "Order approved"),
                    ("order_rejected", "Order rejected"),
                    ("order_packed", "Order packed"),
                    ("out_for_delivery", "Out for delivery"),
                    ("order_delivered", "Order delivered"),
                    ("order_cancelled", "Order cancelled"),
                    ("payment", "Payment update"),
                    ("appointment_booked", "Appointment booked"),
                    ("appointment_confirmed", "Appointment confirmed"),
                    ("appointment_rejected", "Appointment rejected"),
                    ("appointment_completed", "Appointment completed"),
                    ("appointment_cancelled", "Appointment cancelled"),
                    ("diag_booking_requested", "Diagnostic booking requested"),
                    ("diag_booking_confirmed", "Diagnostic booking confirmed"),
                    ("diag_booking_cancelled", "Diagnostic booking cancelled"),
                    ("diag_booking_completed", "Diagnostic booking completed"),
                    ("diag_sample_collected", "Diagnostic sample collected"),
                    ("generic", "Notification"),
                ],
                default="generic",
                max_length=32,
            ),
        ),
    ]
