# Generated by Django 5.2.9 on 2025-12-15 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medicines", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Caegory",
            new_name="Category",
        ),
    ]
