# Generated by Django 5.2.9 on 2025-12-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicines", "0002_rename_caegory_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
