# Generated by Django 5.2.9 on 2025-12-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicines", "0004_category_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
