# Generated by Django 5.2.9 on 2025-12-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicines", "0005_medicine_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicine",
            name="category",
        ),
        migrations.AddField(
            model_name="medicine",
            name="category",
            field=models.ManyToManyField(
                related_name="medicines", to="medicines.category"
            ),
        ),
    ]
