# Generated by Django 5.2.9 on 2025-12-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicines", "0006_remove_medicine_category_medicine_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicine",
            name="slug",
        ),
        migrations.AddField(
            model_name="medicine",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
