# Generated by Django 5.2.9 on 2026-07-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0007_remove_medicine_slug_medicine_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='is_prescription_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicine',
            name='schedule',
            field=models.CharField(choices=[('OTC', 'Over the counter'), ('H', 'Schedule H'), ('H1', 'Schedule H1'), ('X', 'Schedule X')], default='OTC', help_text='Drug schedule classification; H/H1/X require a prescription.', max_length=4),
        ),
    ]
