# Generated by Django 5.2.9 on 2025-12-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="estimated_delivery_end",
        ),
        migrations.RemoveField(
            model_name="order",
            name="estimated_delivery_start",
        ),
        migrations.AddField(
            model_name="order",
            name="estimated_delivery_mins",
            field=models.IntegerField(default=0),
        ),
    ]
