# Generated by Django 5.2.9 on 2026-09-10 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_prescription_reviewed_at_prescription_reviewed_by'),
        ('providers', '0005_provider_address_line1_provider_address_line2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('settled', 'Settled'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, default='', max_length=64)),
                ('note', models.TextField(blank=True, default='')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='providers.provider')),
            ],
            options={
                'ordering': ('-initiated_at',),
            },
        ),
    ]
