# Generated by Django 5.2.9 on 2026-09-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rider_code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
