# Generated by Django 5.2.9 on 2025-12-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("specialty", models.CharField(max_length=255)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("Doctor", "Doctor"),
                            ("Diagnostic Center", "Diagnostic Center"),
                            ("Chemist", "Chemist"),
                            ("Hospital", "Hospital"),
                            ("Nurse", "Nurse"),
                            ("Physiotherapist", "Physiotherapist"),
                            ("Other", "Other"),
                        ],
                        default="Chemist",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
