# Generated by Django 5.2.9 on 2026-09-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_provider_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_type',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Diagnostic Center', 'Diagnostic Center'), ('Lab', 'Lab'), ('Chemist', 'Chemist'), ('Home Healthcare', 'Home Healthcare'), ('Hospital', 'Hospital'), ('Nurse', 'Nurse'), ('Physiotherapist', 'Physiotherapist'), ('Other', 'Other')], default='Chemist', max_length=100),
        ),
    ]
