# Generated by Django 5.2.9 on 2026-09-10 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_provider_address_line1_provider_address_line2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='email',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='phone',
        ),
    ]
