# Generated by Django 5.2.9 on 2025-12-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneOtp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phone_number",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                ("otp", models.CharField(max_length=8)),
            ],
            options={
                "verbose_name": "Phone OTP",
                "verbose_name_plural": "Phone OTPs",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="dob",
            field=models.DateField(blank=True, null=True, verbose_name="Date of Birth"),
        ),
    ]
