# Generated by Django 5.2.9 on 2025-12-15 06:34

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_phoneotp_user_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phoneotp",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                db_index=True, max_length=32, region=None, unique=True
            ),
        ),
    ]
