# Generated by Django 5.2.9 on 2025-12-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="landmark",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
