# Generated by Django 5.2.9 on 2026-09-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_address_options_address_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device',
            field=models.CharField(blank=True, choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='', max_length=16, verbose_name='Last device'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last active'),
        ),
        migrations.AddField(
            model_name='user',
            name='source',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Acquisition source'),
        ),
    ]
