# Generated by Django 5.2.9 on 2026-08-08 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='recording_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='transcript_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='video_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='video_room_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='appointment',
            name='video_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='AppointmentPaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='razorpay', max_length=32)),
                ('transaction_order_id', models.CharField(db_index=True, max_length=128)),
                ('razorpay_payment_id', models.CharField(blank=True, default='', max_length=128)),
                ('razorpay_signature', models.CharField(blank=True, default='', max_length=256)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('succeeded', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='healthcare.appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
