# Generated by Django 5.2.9 on 2026-09-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0002_appointment_video_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostictest',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_picture',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
