# Generated by Django 5.2.9 on 2026-09-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0004_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='degree_document',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='license_document',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
