# Generated by Django 5.2.9 on 2026-09-06 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0005_alter_doctorprofile_degree_document_and_more'),
        ('providers', '0003_provider_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostictest',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='diagnostictest',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_tests', to='providers.provider'),
        ),
        migrations.CreateModel(
            name='DiagnosticPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preparation_instructions', models.TextField(blank=True, default='')),
                ('images', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_packages', to='providers.provider')),
                ('tests', models.ManyToManyField(related_name='packages', to='healthcare.diagnostictest')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='diagnosticbooking',
            name='packages',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='healthcare.diagnosticpackage'),
        ),
    ]
