# Generated by Django 5.2.9 on 2026-09-08 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0006_diagnostictest_mrp_diagnostictest_provider_and_more'),
        ('providers', '0004_dashboard_lab_diagnostic_home_care'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticbooking',
            name='kind',
            field=models.CharField(choices=[('lab', 'Lab'), ('diagnostic', 'Diagnostic'), ('home_healthcare', 'Home Healthcare')], db_index=True, default='lab', max_length=32),
        ),
        migrations.AddField(
            model_name='diagnostictest',
            name='test_kind',
            field=models.CharField(choices=[('lab', 'Lab'), ('imaging', 'Imaging'), ('home_care', 'Home care')], default='lab', max_length=20),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='qualifications_pg',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='qualifications_ug',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='qualification',
            name='level',
            field=models.CharField(choices=[('ug', 'Undergraduate'), ('pg', 'Postgraduate'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='diagnosticbooking',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('sample_collected', 'Sample Collected'), ('report_generated', 'Report Generated'), ('slot_allotted', 'Slot Allotted'), ('patient_arrived', 'Patient Arrived'), ('test_done', 'Test Done'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=32),
        ),
        migrations.CreateModel(
            name='ProviderAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='providers.provider')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('provider', 'day_of_week', 'start_time')},
            },
        ),
    ]
