# Generated by Django 5.2.9 on 2026-09-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0008_supportticket_about_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticbooking',
            name='visit_type',
            field=models.CharField(choices=[('at_centre', 'At Centre'), ('at_home', 'At Home')], default='at_centre', max_length=16),
        ),
    ]
