# Generated by Django 5.2.9 on 2026-09-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0009_diagnosticbooking_visit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='diagnosticbooking',
            name='reports',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='diagnostictest',
            name='sample_type',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
